/* Requires the Docker Pipeline plugin */
pipeline {
    agent any

    environment {
        DockerHub = credentials('dockerhub')
    }

    stages {
        stage('Inspect') { 
            steps {
                sh 'printenv'
                sh 'ls -al'
                sh 'docker --version'
                sh 'docker compose version'
            }
        }

        stage('Build') {
            steps {
                sh 'docker compose build'
            }
        }

        stage('Log in to DockerHub') {
            steps {
                sh 'docker login -u $DockerHub_USR -p $DockerHub_PSW'
            }
        }

        stage('Tag') {
            steps {
                sh 'docker tag de_datapreprocessing $DockerHub_USR/de_datapreprocessing:$(date "+%Y%m%d")-${BUILD_ID}'
                sh 'docker tag de_datapreprocessing $DockerHub_USR/de_datapreprocessing:latest'
            }
        }

        stage('Push') {
            steps {
                
                sh 'docker push $DockerHub_USR/de_datapreprocessing:$(date "+%Y%m%d")-${BUILD_ID}'
                sh 'docker push $DockerHub_USR/de_datapreprocessing:latest'
            }
        }

    }
}
